// Code generated by cmd/protogen from internal/protocol. DO NOT EDIT.

// Messages sent by the client
export type ClientMsg = number;

export const ClientMove: ClientMsg = 1; // Vec, the player's new position
export const ClientWordleGuess: ClientMsg = 2; // WordleReq
export const ClientChat: ClientMsg = 3; // ChatReq
export const ClientWordleStart: ClientMsg = 4; // empty, opens today's wordle

// Messages sent by the server
export type ServerMsg = number;

export const ServerWelcome: ServerMsg = 1; // Welcome, first message after connecting
export const ServerWordleResult: ServerMsg = 2; // WordleRes
export const ServerWordleResume: ServerMsg = 3; // WordleResume
export const ServerChat: ServerMsg = 4; // ChatMsg
export const ServerSnapshot: ServerMsg = 5; // Snapshot

// A position in world pixels
export interface Vec {
    x: number;
    y: number;
}

export interface Welcome {
    playerId: number;
    username: string;
}

export interface PlayerSnap {
    id: number;
    username: string;
    pos: Vec;
}

// Every connected player. Clients replace their view with each one,
// so anyone missing from a snapshot has left.
export interface Snapshot {
    players: Array<PlayerSnap>;
}

export interface ChatReq {
    msg: string;
}

export interface ChatMsg {
    // Player who said it
    id: number;
    msg: string;
}

export type WordleStatus = number;

export const WordleInGame: WordleStatus = 0;
export const WordleWin: WordleStatus = 1;
export const WordleLose: WordleStatus = 2;

export type WordleColor = number;

export const Grey: WordleColor = 0;
export const Yellow: WordleColor = 1;
export const Green: WordleColor = 2;

export interface WordleReq {
    guess: string;
}

export interface WordleRes {
    valid: boolean;
    status: WordleStatus;
    colors: Array<WordleColor>;
    solution: string;
    seconds: number;
}

// Sent in reply to ClientWordleStart, the guesses already made today
export interface WordleResume {
    guesses: Array<string>;
    colors: Array<Array<WordleColor>>;
    seconds: number;
}
