// Code generated by cmd/protogen from internal/protocol. DO NOT EDIT.

// Messages sent by the client
export type ClientMsg = number;

export const ClientMove: ClientMsg = 1; // Vec, the player's new position
export const ClientWordleGuess: ClientMsg = 2; // WordleReq
export const ClientChat: ClientMsg = 3; // ChatReq
export const ClientWordleStart: ClientMsg = 4; // empty, opens today's wordle

// Messages sent by the server
export type ServerMsg = number;

export const ServerWelcome: ServerMsg = 1; // Welcome, first message after connecting
export const ServerWordleResult: ServerMsg = 2; // WordleRes
export const ServerWordleResume: ServerMsg = 3; // WordleResume
export const ServerChat: ServerMsg = 4; // ChatMsg
export const ServerWorld: ServerMsg = 5; // WorldUpdate
export const ServerCorrection: ServerMsg = 6; // Vec, the server rejected a move, snap back here

// A position in world pixels
export interface Vec {
    x: number;
    y: number;
}

export type EntityID = number;

export type EntityKind = number;

export const EntityPlayer: EntityKind = 1;

export interface Welcome {
    playerId: number;
    username: string;
    // The entity that is you. It is never sent in WorldUpdates, you move it yourself.
    entityId: EntityID;
    pos: Vec;
    map: WorldMap;
    // Fastest a player may move in px/s, faster moves are corrected
    moveSpeed: number;
    tickRate: number;
}

// The static world, loaded from a JSON map file
export interface WorldMap {
    width: number;
    height: number;
    background: string;
    spawn: Vec;
    interactables: Array<Interactable>;
}

// Something in the world a player can click
export interface Interactable {
    id: string;
    sprite: string;
    pos: Vec;
    w: number;
    h: number;
    // What the client does when it's clicked, e.g. "wordle"
    action: string;
}

// Changes to the entities near you since the last update. Only sent when
// something changed.
export interface WorldUpdate {
    // Entities that came into view
    spawn?: Array<EntitySpawn>;
    // Known entities that moved
    move?: Array<EntityMove>;
    // Entities that left view or the game
    despawn?: Array<EntityID>;
}

export interface EntitySpawn {
    id: EntityID;
    kind: EntityKind;
    name: string;
    sprite: string;
    pos: Vec;
}

// Sent as [id, x, y] to keep moves small
export type EntityMove = [id: EntityID, x: number, y: number];

export interface ChatReq {
    msg: string;
}

export interface ChatMsg {
    // Entity who said it
    id: EntityID;
    msg: string;
}

export type WordleStatus = number;

export const WordleInGame: WordleStatus = 0;
export const WordleWin: WordleStatus = 1;
export const WordleLose: WordleStatus = 2;

export type WordleColor = number;

export const Grey: WordleColor = 0;
export const Yellow: WordleColor = 1;
export const Green: WordleColor = 2;

export interface WordleReq {
    guess: string;
}

export interface WordleRes {
    valid: boolean;
    status: WordleStatus;
    colors: Array<WordleColor>;
    solution: string;
    seconds: number;
}

// Sent in reply to ClientWordleStart, the guesses already made today
export interface WordleResume {
    guesses: Array<string>;
    colors: Array<Array<WordleColor>>;
    seconds: number;
}
