// Package tsgen turns the Go message definitions in internal/protocol into
// TypeScript, so the client and server can't drift apart.
//
// It supports what the protocol needs: exported structs (field names from msgpack
// tags, as_array structs become tuples), named basic types, slices, maps, and
// typed constants with literal values.
package tsgen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
)

const header = "// Code generated by cmd/protogen from internal/protocol. DO NOT EDIT.\n"

// Generates TypeScript for the exported types and constants of the Go package in dir
func Generate(dir string) ([]byte, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "*.go"))
	if err != nil {
		return nil, err
	}
	sort.Strings(paths)

	var out bytes.Buffer
	out.WriteString(header)

	fset := token.NewFileSet()
	for _, path := range paths {
		if strings.HasSuffix(path, "_test.go") {
			continue
		}
		src, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		file, err := parser.ParseFile(fset, path, src, parser.ParseComments)
		if err != nil {
			return nil, err
		}
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok {
				continue
			}
			var err error
			switch gd.Tok {
			case token.TYPE:
				err = genTypes(&out, gd)
			case token.CONST:
				err = genConsts(&out, gd)
			}
			if err != nil {
				return nil, fmt.Errorf("%s: %w", fset.Position(gd.Pos()), err)
			}
		}
	}
	return out.Bytes(), nil
}

func writeDoc(out *bytes.Buffer, groups ...*ast.CommentGroup) {
	for _, g := range groups {
		if g == nil {
			continue
		}
		for _, line := range strings.Split(strings.TrimSpace(g.Text()), "\n") {
			fmt.Fprintf(out, "// %s\n", line)
		}
		return
	}
}

func genTypes(out *bytes.Buffer, gd *ast.GenDecl) error {
	for _, spec := range gd.Specs {
		ts := spec.(*ast.TypeSpec)
		if !ts.Name.IsExported() {
			continue
		}
		out.WriteString("\n")
		writeDoc(out, ts.Doc, gd.Doc)

		st, ok := ts.Type.(*ast.StructType)
		if !ok {
			t, err := tsType(ts.Type)
			if err != nil {
				return err
			}
			fmt.Fprintf(out, "export type %s = %s;\n", ts.Name.Name, t)
			continue
		}

		fields, asArray, err := structFields(st)
		if err != nil {
			return fmt.Errorf("%s: %w", ts.Name.Name, err)
		}
		if asArray {
			parts := make([]string, len(fields))
			for i, f := range fields {
				// Tuple labels are just documentation, match TS style
				label := strings.ToLower(f.name[:1]) + f.name[1:]
				if strings.ToUpper(f.name) == f.name {
					label = strings.ToLower(f.name) // ID -> id
				}
				parts[i] = label + ": " + f.typ
			}
			fmt.Fprintf(out, "export type %s = [%s];\n", ts.Name.Name, strings.Join(parts, ", "))
			continue
		}
		fmt.Fprintf(out, "export interface %s {\n", ts.Name.Name)
		for _, f := range fields {
			for _, line := range f.doc {
				fmt.Fprintf(out, "    // %s\n", line)
			}
			fmt.Fprintf(out, "    %s: %s;\n", f.name, f.typ)
		}
		out.WriteString("}\n")
	}
	return nil
}

type field struct {
	name string
	typ  string
	doc  []string
}

func structFields(st *ast.StructType) (fields []field, asArray bool, err error) {
	for _, f := range st.Fields.List {
		tag := ""
		if f.Tag != nil {
			tag = reflect.StructTag(strings.Trim(f.Tag.Value, "`")).Get("msgpack")
		}
		if len(f.Names) == 0 {
			return nil, false, fmt.Errorf("embedded fields are not supported")
		}
		for _, name := range f.Names {
			if name.Name == "_msgpack" {
				asArray = strings.Contains(tag, "as_array")
				continue
			}
			if !name.IsExported() {
				continue
			}
			opts := strings.Split(tag, ",")
			key := opts[0]
			if key == "-" {
				continue
			}
			if key == "" {
				key = name.Name
			}
			typ, err := tsType(f.Type)
			if err != nil {
				return nil, false, fmt.Errorf("field %s: %w", name.Name, err)
			}
			var doc []string
			if f.Doc != nil {
				doc = strings.Split(strings.TrimSpace(f.Doc.Text()), "\n")
			}
			// omitempty fields may be missing
			for _, opt := range opts[1:] {
				if opt == "omitempty" {
					key += "?"
				}
			}
			fields = append(fields, field{name: key, typ: typ, doc: doc})
		}
	}
	return fields, asArray, nil
}

func tsType(expr ast.Expr) (string, error) {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64", "byte", "rune":
			return "number", nil
		case "string":
			return "string", nil
		case "bool":
			return "boolean", nil
		case "any":
			return "unknown", nil
		}
		if !t.IsExported() {
			return "", fmt.Errorf("unexported type %s", t.Name)
		}
		return t.Name, nil
	case *ast.ArrayType:
		if t.Len != nil {
			return "", fmt.Errorf("fixed size arrays are not supported")
		}
		elem, err := tsType(t.Elt)
		if err != nil {
			return "", err
		}
		return "Array<" + elem + ">", nil
	case *ast.MapType:
		k, err := tsType(t.Key)
		if err != nil {
			return "", err
		}
		v, err := tsType(t.Value)
		if err != nil {
			return "", err
		}
		return "Record<" + k + ", " + v + ">", nil
	case *ast.StarExpr:
		elem, err := tsType(t.X)
		if err != nil {
			return "", err
		}
		return elem + " | null", nil
	case *ast.InterfaceType:
		return "unknown", nil
	case *ast.SelectorExpr:
		// e.g. msgpack.RawMessage, already decoded by the time the client sees it
		return "unknown", nil
	}
	return "", fmt.Errorf("unsupported type %T", expr)
}

func genConsts(out *bytes.Buffer, gd *ast.GenDecl) error {
	wrote := false
	for _, spec := range gd.Specs {
		vs := spec.(*ast.ValueSpec)
		for i, name := range vs.Names {
			if !name.IsExported() {
				continue
			}
			if vs.Type == nil || i >= len(vs.Values) {
				return fmt.Errorf("const %s needs an explicit type and value", name.Name)
			}
			lit, ok := vs.Values[i].(*ast.BasicLit)
			if !ok {
				return fmt.Errorf("const %s must be a literal", name.Name)
			}
			typ, err := tsType(vs.Type)
			if err != nil {
				return err
			}
			if !wrote {
				out.WriteString("\n")
				writeDoc(out, gd.Doc)
				wrote = true
			}
			writeDoc(out, vs.Doc)
			line := ""
			if vs.Comment != nil {
				line = " // " + strings.TrimSpace(vs.Comment.Text())
			}
			fmt.Fprintf(out, "export const %s: %s = %s;%s\n", name.Name, typ, lit.Value, line)
		}
	}
	return nil
}
